### ISSUE TITLE
`GLIBCXX_3.4.26' not found

### ISSUE THREAD

**Issue by seliqui** [lens-protocol/momoka#10]
I'm having problems getting the verifier started, seems like because GLIBCXX v3.4.26 can't be found.

Errror Message:
```
seliqui@32709:~/momoka-verifier$ momoka --node 'https://polygon-mainnet.g.alchemy.com/v2/VD_EooBfohR2pk3abgpIpx5jVfhLwi-w' --environment='POLYGON' --concurrency=20 --fromHead=false
node:internal/modules/cjs/loader:1338
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: /lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by /home/seliqui/.nvm/versions/node/v18.16.0/lib/node_modules/@lens-protocol/momoka/node_modules/node-libcurl/lib/binding/node_libcurl.node)
    at Module._extensions..node (node:internal/modules/cjs/loader:1338:18)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (/home/seliqui/.nvm/versions/node/v18.16.0/lib/node_modules/@lens-protocol/momoka/node_modules/node-libcurl/dist/Easy.js:5:18)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (/home/seliqui/.nvm/versions/node/v18.16.0/lib/node_modules/@lens-protocol/momoka/node_modules/node-libcurl/dist/Curl.js:17:16)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32) {
  code: 'ERR_DLOPEN_FAILED'
}

Node.js v18.16.0

```

Process:
1.) Installed the Momoka Package via `npm i @lens-protocol/momoka -g`
2.) Tried running it via `momoka --node 'https://polygon-mainnet.g.alchemy.com/v2/VD_EooBfohR2pk3abgpIpx5jVfhLwi-w' --environment='POLYGON' --concurrency=20 --fromHead=false`

Attempts to fix it myself:
* `sudo apt update` and `sudo apt upgrade` 
* `sudo apt install build-essential` 
* Switched NodeJS Versions, from an older one (16x) to recent LTS (18x) to newest (20.x)
* Directly `sudo apt install libstdc++6`  (which returns that newest version of libstdc++6 is already installed - 8.3.0-6).

Checking the installed versions of libstdc++ via `strings /usr/lib/x86_64-linux-gnu/libstdc++.so.6 | grep GLIBCXX` returns:
```
GLIBCXX_3.4
GLIBCXX_3.4.1
GLIBCXX_3.4.2
GLIBCXX_3.4.3
GLIBCXX_3.4.4
GLIBCXX_3.4.5
GLIBCXX_3.4.6
GLIBCXX_3.4.7
GLIBCXX_3.4.8
GLIBCXX_3.4.9
GLIBCXX_3.4.10
GLIBCXX_3.4.11
GLIBCXX_3.4.12
GLIBCXX_3.4.13
GLIBCXX_3.4.14
GLIBCXX_3.4.15
GLIBCXX_3.4.16
GLIBCXX_3.4.17
GLIBCXX_3.4.18
GLIBCXX_3.4.19
GLIBCXX_3.4.20
GLIBCXX_3.4.21
GLIBCXX_3.4.22
GLIBCXX_3.4.23
GLIBCXX_3.4.24
GLIBCXX_3.4.25
GLIBCXX_DEBUG_MESSAGE_LENGTH
```

Which miss the needed 3.4.26 version ^^

Some additional infos:
nvm version: 0.38.0
active node version: v18.16.0
libstdc++6 version: 8.3.0-6
System: Debian 10 (Buster) / Server

**Comment by seliqui** [comment]
Update:

Upgraded from Debian 10 (Buster) to Debian 11 (Bullseye).
Now `GLIBCXX_3.4.26` is avaiable, and the verifier started ✌️

**Comment by joshstevens19** [comment]
Amazing
