### ISSUE TITLE
Error deploying with npm

### ISSUE THREAD

**Issue by polibee** [lens-protocol/momoka#14]
npm WARN config init.module Use `--init-module` instead.
/root/node_modules/@lens-protocol/momoka/lib/graphql/urql.client.js:9
    fetch: fetch,
           ^

ReferenceError: fetch is not defined
    at Object.<anonymous> (/root/node_modules/@lens-protocol/momoka/lib/graphql/urql.client.js:9:12)
    at Module._compile (node:internal/modules/cjs/loader:1155:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1209:10)
    at Module.load (node:internal/modules/cjs/loader:1033:32)
    at Function.Module._load (node:internal/modules/cjs/loader:868:12)
    at Module.require (node:internal/modules/cjs/loader:1057:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (/root/node_modules/@lens-protocol/momoka/lib/input-output/bundlr/get-data-availability-transactions.api.js:5:23)
    at Module._compile (node:internal/modules/cjs/loader:1155:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1209:10)

Can the project owner provide a docker image for momoka users to easily deploy?

**Comment by joshstevens19** [comment]
Docker instructions exist on the readme - your error above looks like you not got the correct node version installed

**Comment by polibee** [comment]
Can you share the runtime environment?
